accent = "#006540"
cursor = "#00a86b"
foreground = "#e6f6f0"
background = "#00110b"
selection_foreground = "#00110b"
selection_background = "#CCCC99"

color0 = "#00110b"
color1 = "#ff3370"
color2 = "#00a86b"
color3 = "#cceee1"
color4 = "#006540"
color5 = "#C3FCB8"
color6 = "#80d4b5"
color7 = "#e6f6f0"
color8 = "#003220"
color9 = "#ff3370"
color10 = "#00a86b"
color11 = "#cceee1"
color12 = "#006540"
color13 = "#C3FCB8"
color14 = "#80d4b5"
color15 = "#e6f6f0"
