
# ========= Border =========
file_panel_border = '#e6f6f0'
sidebar_border = '#e6f6f0'
footer_border = '#e6f6f0'

# ========= Border Active =========
file_panel_border_active = '#D1FFb0'
sidebar_border_active = '#D1FFb0'
footer_border_active = '#D1FFb0'
modal_border_active = '#D1FFb0'

# ========= Background (bg) =========
full_screen_bg = '#00110b'
file_panel_bg = '#00110b'
sidebar_bg = '#00110b'
footer_bg = '#00110b'
modal_bg = '#00110b'

# ========= Foreground (fg) =========
full_screen_fg = '#e6f6f0'
file_panel_fg = '#e6f6f0'
sidebar_fg = '#e6f6f0'
footer_fg = '#e6f6f0'
modal_fg = '#e6f6f0'

# ========= Special Color =========
cursor = '#e6f6f0'
correct = '#00a86b'
error = '#ff3370'
hint = '#80d4b5'
cancel = '#ff3370'
gradient_color = ['#00110b', "#87ae83"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#00110b'
file_panel_top_path = '#87ae83'
file_panel_item_selected_fg = '#87ae83'
file_panel_item_selected_bg = '#00110b'

# ========= Sidebar Special Items =========
sidebar_title = '#e6f6f0'
sidebar_item_selected_fg = '#87ae83'
sidebar_item_selected_bg = '#00110b'
sidebar_divider = '#e6f6f0'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#ff3370'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#00a86b'
